// tokens:gen — emits a typed token map from the design-system manifest for use
// in logic (STATUS/SOURCE lookups, tests). The CSS custom properties remain the
// runtime contract; this file is generated, never hand-edited. (Run: npm run tokens:gen)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const manifest = JSON.parse(readFileSync(join(root, 'design-system-manifest.json'), 'utf8'))
const tokens = manifest.tokens ?? []
// Output directory is overridable so the drift check (scripts/check-tokens-drift.mjs)
// can regenerate to a temp path and diff, WITHOUT writing into src/. One generator,
// one set of generation logic — a drift checker that reimplemented this would drift
// from it, which is the failure it exists to catch.
const outFlag = process.argv.indexOf('--out')
const outDir = outFlag !== -1 && process.argv[outFlag + 1] ? process.argv[outFlag + 1] : join(root, 'src/tokens')
mkdirSync(outDir, { recursive: true })

const entries = tokens.map((t) => `  '${t.name}': ${JSON.stringify(t.value)},`).join('\n')
const names = tokens.map((t) => `  | '${t.name}'`).join('\n')

const out = `// AUTO-GENERATED by scripts/gen-tokens.mjs from design-system-manifest.json.
// Do not edit by hand. The CSS custom properties are the runtime contract;
// this typed map is for logic (lookups, tests, the token-diff gate).
/* eslint-disable */

export const tokens = {
${entries}
} as const

export type TokenName =
${names}

/** \`var(--token)\` helper with autocomplete over known token names. */
export function cssVar(name: TokenName): string {
  return \`var(\${name})\`
}
`
writeFileSync(join(outDir, 'tokens.generated.ts'), out)
console.log(`✓ tokens:gen wrote ${tokens.length} tokens → src/tokens/tokens.generated.ts`)
